<?php

/**
 * @file
 * Functions to support theming in the collectorsystems theme.
 */

function collector_systems_preprocess_page(&$variables){
  $variables['#cache']['max-age'] = 0;
}

/**
 * Implements hook_theme().
 */
function collector_systems_theme() {
  return [
    'objects-list-page' => [
      'variables' => [
        'object_details' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL
      ],
    ],
    'artists-list-page' => [
      'variables' => [
        'AllArtists' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'requested_page' => NULL,
        'collector_systems_module_path' => NULL
      ],
    ],
    'exhibitions-list-page' => [
      'variables' => [
        'all_exhibitions' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
      ],
    ],
    'groups-list-page' => [
      'variables' => [
        'all_groups' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
      ],
    ],
    'collections-list-page' => [
      'variables' => [
        'all_collections' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_page' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'site_url' => NULL
      ],
    ],
    'artobject-detail-page' => [
      'variables' => [
        'thumbDetails' => NULL,
        'customized_fields_array' => NULL,
        'object_details' => NULL,
        'row_number' => NULL,
        'row_before' => NULL,
        'row_after' => NULL,
        'count' => NULL,
        'sortBy' =>NULL,
        'qSearch' => NULL,
        'requested_pageNo' => NULL,
      ],
    ],
    'artist-detail-page' => [
      'variables' => [
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'obj_count' => NULL,
        'artistId' => NULL,
        'groupLevelOrderBy' => NULL,
        'groupLevelPageNo' => NULL,
        'artist_details' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'object_details' => NULL,
        'listPageSize' => NULL,
        'ajaxfor' => NULL,
        'collector_systems_module_path' => NULL
      ],
    ],
    'exhibition-detail-page' => [
      'variables' => [
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'obj_count' => NULL,
        'groupLevelOrderBy' => NULL,
        'groupLevelPageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'object_details' => NULL,
        'exhibitionID' => NULL,
        'exhibition_details' => NULL,
        'listPageSize' => NULL,
        'ajaxfor' => NULL,
      ],
    ],
    'group-detail-page' => [
      'variables' => [
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'obj_count' => NULL,
        'groupLevelOrderBy' => NULL,
        'groupLevelPageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'object_details' => NULL,
        'group_details' => NULL,
        'groupID' => NULL,
        'group_object_details' => NULL,
        'listPageSize' => NULL,
        'ajaxfor' => NULL,
      ],
    ],
    'collection-detail-page' => [
      'variables' => [
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'obj_count' => NULL,
        'groupLevelOrderBy' => NULL,
        'groupLevelPageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'object_details' => NULL,
        'collectionID' => NULL,
        'collection_details' => NULL,
        'listPageSize' => NULL,
        'ajaxfor' => NULL,
      ],
    ],



  ];


}
