<?php
use Drupal\Core\Database\Database;
use Drupal\Core\Database\Schema;
use Drupal\custom_api_integration\Csconstants;
use Drupal\menu_link_content\Entity\MenuLinkContent;

/**
 * Creates menu items in the main navigation menu if there are no menu items created for list pages
 */
function create_main_menu_items(){
  // Array of menu items for the main menu
  $main_menu_items = array(
    array(
      'title' => 'Objects',
      'link' => 'route:custom_api_integration.objects_list_page',
      'menu_name' => 'main',
      'expanded' => TRUE,
      'weight' => 0,

    ),
    array(
      'title' => 'Artists',
      'link' => 'route:custom_api_integration.artists_list_page',
      'menu_name' => 'main',
      'expanded' => TRUE,
      'weight' => 1,

    ),
    array(
      'title' => 'Exhibitions',
      'link' => 'route:custom_api_integration.exhibitions_list_page',
      'menu_name' => 'main',
      'expanded' => TRUE,
      'weight' => 2,

    ),
    array(
      'title' => 'Groups',
      'link' => 'route:custom_api_integration.groups_list_page',
      'menu_name' => 'main',
      'expanded' => TRUE,
      'weight' => 3,
    ),
    array(
      'title' => 'Collectons',
      'link' => 'route:custom_api_integration.collections_list_page',
      'menu_name' => 'main',
      'expanded' => TRUE,
      'weight' => 4,

    ),
    // Add more main menu items as needed
  );

  // Iterate through the array and create main menu items
  foreach ($main_menu_items as $item) {
    $existing_menu_item = \Drupal::entityTypeManager()
    ->getStorage('menu_link_content')
    ->loadByProperties(['link' => $item['link']]);

    if (empty($existing_menu_item)) {
      // Menu item does not exist, create it
      $menu_link = MenuLinkContent::create($item);
      $menu_link->save();
    }
  }
}
/**
 * Implements hook_theme().
 */
function custom_api_integration_theme() {
  return [
    'custom_api_integration_response' => [
      'variables' => [
        'response' => '',
        'show_field_labels' => '',
        'enable_zoom' => '',
        'filter_keywords' => '',
        'items_per_page' => '',
        'footer_text' => '',
      ],
    ],
    'dashboard' => [
      'variables' => [
        'response' => '',
        'show_field_labels' => '',
        'enable_zoom' => '',
        'filter_keywords' => '',
        'items_per_page' => '',
        'footer_text' => '',
      ],
    ],
    'objects-list-page' => [
      'variables' => [
        'object_details' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL
      ],
    ],
    'artists-list-page' => [
      'variables' => [
        'AllArtists' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'requested_page' => NULL
      ],
    ],
    'exhibitions-list-page' => [
      'variables' => [
        'all_exhibitions' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
      ],
    ],
    'groups-list-page' => [
      'variables' => [
        'all_groups' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
      ],
    ],
    'collections-list-page' => [
      'variables' => [
        'all_collections' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_page' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'site_url' => NULL
      ],
    ],
    'artobject-detail-page' => [
      'variables' => [
        'thumbDetails' => NULL,
        'customized_fields_array' => NULL,
        'object_details' => NULL,
        'row_number' => NULL,
        'row_before' => NULL,
        'row_after' => NULL,
        'count' => NULL,
        'sortBy' =>NULL,
        'qSearch' => NULL,
        'requested_pageNo' => NULL,
      ],
    ],
    'artist-detail-page' => [
      'variables' => [
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'obj_count' => NULL,
        'artistId' => NULL,
        'groupLevelOrderBy' => NULL,
        'groupLevelPageNo' => NULL,
        'artist_details' => NULL,
        'groupLevelPageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'object_details' => NULL,
        'ajaxfor' => NULL,
      ],
    ],
    'exhibition-detail-page' => [
      'variables' => [
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'obj_count' => NULL,
        'groupLevelOrderBy' => NULL,
        'groupLevelPageNo' => NULL,
        'groupLevelPageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'object_details' => NULL,
        'exhibitionID' => NULL,
        'exhibition_details' => NULL
      ],
    ],
    'group-detail-page' => [
      'variables' => [
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'obj_count' => NULL,
        'groupLevelOrderBy' => NULL,
        'groupLevelPageNo' => NULL,
        'groupLevelPageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'object_details' => NULL,
        'group_details' => NULL,
        'groupID' => NULL,
        'group_object_details' => NULL
      ],
    ],
    'collection-detail-page' => [
      'variables' => [
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'obj_count' => NULL,
        'groupLevelOrderBy' => NULL,
        'groupLevelPageNo' => NULL,
        'groupLevelPageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'object_details' => NULL,
        'collectionID' => NULL,
        'collection_details' => NULL,
      ],
    ]


  ];
}
/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function custom_api_integration_preprocess_page(&$variables)
{
    $variables['#attached']['library'][] = 'custom_api_integration/custom_api_integration';
    create_main_menu_items();
}
