<?php
use Drupal\Core\Database\Database;
use Drupal\Core\Database\Schema;
use Drupal\custom_api_integration\Csconstants;

/**
 * Implements hook_theme().
 */
function custom_api_integration_theme() {
  return [
    'custom_api_integration_response' => [
      'variables' => [
        'response' => '',
        'show_field_labels' => '',
        'enable_zoom' => '',
        'filter_keywords' => '',
        'items_per_page' => '',
        'footer_text' => '',
      ],
    ],
    'dashboard' => [
      'variables' => [
        'response' => '',
        'show_field_labels' => '',
        'enable_zoom' => '',
        'filter_keywords' => '',
        'items_per_page' => '',
        'footer_text' => '',
      ],
    ],
    'objects-list-page' => [
      'variables' => [
        'object_details' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL
      ],
    ],
    'artists-list-page' => [
      'variables' => [
        'AllArtists' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
        'requested_page' => NULL
      ],
    ],
    'exhibitions-list-page' => [
      'variables' => [
        'all_exhibitions' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
      ],
    ],
    'groups-list-page' => [
      'variables' => [
        'all_groups' =>NULL,
        'nxshowrec' => NULL,
        'nxshskip' => NULL,
        'count' => NULL,
        'dataorderby' => NULL,
        'current_page' => NULL,
        'requested_pageNo' => NULL,
        'qSearch' => NULL,
        'loadsec' => NULL,
      ],
    ]
  ];
}
/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function custom_api_integration_preprocess_page(&$variables)
{
    $variables['#attached']['library'][] = 'custom_api_integration/custom_api_integration';
}


