<?php

use Drupal\custom_api_integration\Csconstants;

/**
 * Implements hook_theme().
 */
function custom_api_integration_theme() {
  return [
    'custom_api_integration_response' => [
      'variables' => [
        'response' => '',
        'show_field_labels' => '',
        'enable_zoom' => '',
        'filter_keywords' => '',
        'items_per_page' => '',
        'footer_text' => '',
      ],
    ],
    'dashboard' => [
      'variables' => [
        'response' => '',
        'show_field_labels' => '',
        'enable_zoom' => '',
        'filter_keywords' => '',
        'items_per_page' => '',
        'footer_text' => '',
        'API_Synced_On' => '',
        'API_Synced_By' => ''
      ],
    ],



  ];
}


function getObjectImageAttachmentsByObjectId($artObjID, $mainAttachmentId)
{

  $config = \Drupal::config('custom_api_integration.settings');
  $subsKey = $config->get('subscription_key');
  $subAcntId = $config->get('account_guid');
  $subsId = $config->get('subscription_id');
  $filterImagesByKeywords = $config->get('filter_keywords');
  $keywordsArray = [];
  foreach($filterImagesByKeywords as $key => $value){
    $keywordsArray[] = $key;
  }
  $filterKeywordsUrl = "";
  if($keywordsArray)
  {
    $keywordIndex=0;
    foreach($keywordsArray as $keywordString)
    {
        if($keywordIndex==0)
        {
            $filterKeywordsUrl.='attachmentKeywords/AttachmentKeywordString%20eq%20%27'.rawurlencode($keywordString).'%27';
        }
        else
        {
            $filterKeywordsUrl.='%20OR%20attachmentKeywords/AttachmentKeywordString%20eq%20%27'.rawurlencode($keywordString).'%27';
        }
        $keywordIndex=$keywordIndex+1;
    }



    //match keywords or attachment is main attachment
    $url = csconstants::Public_API_URL.$subAcntId.'/ObjectImageAttachments?$expand=Attachment($expand=AttachmentKeywords($select=AttachmentKeywordString);$select=AttachmentId,SubscriptionId,FileName,Description,DetailLargeURL,DetailXLargeURL,FileURL,ThumbSizeURL)&$filter=ObjectId%20eq%20'.$artObjID.'%20And%20SubscriptionId%20eq%20'.$subsId.'And%20((Attachment/AttachmentKeywords/any(attachmentKeywords:'.$filterKeywordsUrl.'))%20OR%20AttachmentId%20eq%20'.$mainAttachmentId.')&$select=AttachmentId,ObjectId';

    echo '<script>console.log("attachments url: ' . $url . '")</script>';
    // return $d = checkshortfunction($url, $subsKey);


    //call the api
    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

    $headers = array(
    "Accept: application/json",
    "Ocp-Apim-Subscription-Key:$subsKey ",
    "Cache-Control:no-cache",
    );
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    //for debug only!
    curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

    $data = curl_exec($curl);
    curl_close($curl);

    $httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
    if($httpcode == 403)
    {
      // get_template_part( 403 );
      exit();
    }
    $data = json_decode($data, TRUE);
    return $data['value'] ?? null;

  }else{
    return null;
  }

}

/*
*Returns the array of filtered keywords
*/
function get_filtered_keywords(){
  $config = \Drupal::config('custom_api_integration.settings');
  $subsKey = $config->get('subscription_key');
  $subAcntId = $config->get('account_guid');
  $subsId = $config->get('subscription_id');
  $filterImagesByKeywords = $config->get('filter_keywords');
  $keywordsArray = [];
  foreach($filterImagesByKeywords as $key => $value){
    $keywordsArray[] = $key;
  }

  return $keywordsArray;
}
