module.settings:
  type: config_object
  label: 'Custom Fields Display Settings'
  mapping:
    content_type:
      type: string
      label: 'Content Type'
    selected_fields:
      type: sequence
      label: 'Selected Fields'
      sequence:
        type: string
